### ISSUE TITLE
cordova-spotify.min.js.map error

### ISSUE THREAD

**Issue by rijink7** [Festify/cordova-spotify#46]
![screen shot 2018-11-22 at 8 01 12 pm](https://user-images.githubusercontent.com/20573969/48908883-aa527780-ee91-11e8-958c-363327f7c7a3.png)

the build was successful but it shows this error. How to solve it ?

**Comment by shi11** [comment]
I'm seeing this aswell. I did some googling and saw a similar issue here: https://github.com/Festify/cordova-spotify-oauth/issues/4 however it looks like the travis.yml in this project already has the fix?? So I'm at a loss. @rijink7 any luck?

**Comment by shi11** [comment]
Solved by updating node to v10.

**Comment by jonbongato** [comment]
Hi,

I'm experiencing the same issue. Updated Node to v10 and it still doesn't work. 

Getting a 'player_init_failed: The Spotify library failed to initialize' error.
